version: "3"

services:
  testdb:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: aritimetica
      POSTGRES_PASSWORD: aritimetica
      POSTGRES_DB: aritimetica
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: examplepassword
    ports:
      - "5050:80"
    links:
      - testdb
volumes:
  postgres:

