version: '3'

services:
  devdb:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
    environment:
      POSTGRES_USER: aritimeticau
      POSTGRES_PASSWORD: aritimeticap
      POSTGRES_DB: aritimeticad
    ports:
      - '5432:5432'
  testdb:
    image: postgres
    volumes:
      - postgres:/var/lib/postgresql/data_test/
      - ./logs:/var/lib/postgresql/data/pg_log
    environment:
      POSTGRES_USER: aritimeticau
      POSTGRES_PASSWORD: aritimeticap
      POSTGRES_DB: aritimeticad
    ports:
      - '5433:5432'
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: example@example.com
      PGADMIN_DEFAULT_PASSWORD: examplepassword
    ports:
      - '5050:80'
    links:
      - testdb
      - devdb
volumes:
  postgres:
